services:
  or-balance:
    build: .
    image: helper:latest
    env_file:
      - .env
    ports:
      - "8000:8000"
    volumes:
      - ./.env:/app/.env
    restart: always
#     networks:
#       - default
#       - or-net
#     volumes:
#       - or-data:/data

# volumes:
#   or-data:

# networks:
#   or-net:
#     name: or-net
#     external: true