services:
  or-balance:
    image: helper:latest
    env_file:
      - .env
    restart: always
#     networks:
#       - default
#       - or-net
#     volumes:
#       - or-data:/data

# volumes:
#   or-data:

# networks:
#   or-net:
#     name: or-net
#     external: true